spring:
  application:
    name : 22-tenten-be
  datasource:
    url: ${MYSQL_URL}
    username: root
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000


app:
  jwt:
    secret: ${JWT_SECRET}
    secure: true
    issuer: kakaobase
    audience: web
    access:
      expiration-time: 1800000 # 30분
    refresh:
      expiration-time: 604800000 # 7일
      token-name: kakaobase_refresh_token
      path: /auth/tokens/refresh
