spring:
  config:
    activate:
      on-profile: dev
    import: optional:aws-parameterstore:/kakaobase/dev/

app:
  jwt:
    secure: false
    refresh:
      domain: ${COOKIE_DOMAIN}
      same-site: Lax

logging:
  level:
    com.amazonaws.util.EC2MetadataUtils: ERROR
    com.amazonaws.services.s3: INFO
    com.kakaobase.snsapp.global.security: DEBUG
    com.kakaobase.snsapp.domain.auth: DEBUG
    com.kakaobase.snsapp.domain.posts: DEBUG
    org.springframework.security: DEBUG