spring:
  application:
    name : 22-tenten-be
  datasource:
    url: ${MYSQL_URL}
    username: root
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 20          # 기존 10 → 20
      maximum-pool-size: 70     # 기존 10 → 70
      connection-timeout: 30000 # (기존 30000 유지)
      idle-timeout: 600000      # (기존 600000 유지)
      max-lifetime: 1800000     # (기존 1800000 유지)
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
  security:
    debug: true
  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}
        instance-profile: true
      region:
        static: ap-northeast-2
      s3:
        bucket: ${BUCKET_NAME}

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000


app:
  jwt:
    secret: ${JWT_SECRET}
    issuer: kakaobase
    audience: web
    access:
      expiration-time: 1800000 # 30분
    refresh:
      expiration-time: 604800000 # 7일
      token-name: kakaobase_refresh_token
      path: api/auth/tokens
  s3:
    expiration-time: 300
    max-file-size: 10485760

ai:
  server:
    url: ${AI_SERVER_URL}

server:
  forward-headers-strategy: framework
  tomcat:
    mbeanregistry:
      enabled: true

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health,info,metrics,env,beans,jmx

  endpoint:
    health:
      enabled: true
      show-details: never
    jmx:
      enabled: true

  health:
    defaults:
      enabled: false   # ① 모든 Indicator 비활성화
    diskspace:
      enabled: false   # ② DiskSpace 자동 체크도 비활성화 (필요 없으면)
    db:
      enabled: false   # ③ DB 체크 해제
    redis:
      enabled: false   # ④ Redis 체크 해제
    mail:
      enabled: false   # ⑤ Mail 체크 해제